# Generated by Django 5.2.6 on 2025-09-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('result', models.CharField(choices=[('H', 'Home Win'), ('A', 'Away Win'), ('D', 'Draw')], max_length=1)),
                ('season', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['date'],
            },
        ),
    ]
